name: SALÓN DE JULIO
markdown: kramdown
highlighter: rouge
exclude: [main.scss, config.rb]
description: Sitio informativo del Programa Museo, Arte y Ciudad - Salón de Julio 2017
url: http://www.salondejulio.com/
permalink: pretty
