name: SALÓN DE JULIO
markdown: kramdown
highlighter: rouge

port: 8000

exclude: [main.scss, config.rb]
description: Sitio informativo del Programa Museo, Arte y Ciudad - Salón de Julio 2018
url: https://www.salondejulio.com/
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty

collections:
  projects:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project
